version: '3.4'

services:
  webapi:
    container_name: aspnetcore-keycloak-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: aspnetcore-keycloak-mssql
    # restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abcd1234! # Server=sqlserver;Database=naos_sample;User=sa;Password=Abcd1234!;Trusted_Connection=False;MultipleActiveResultSets=True;
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - mssql:/var/opt/mssql

  mssqlscripts:
    image: mcr.microsoft.com/mssql-tools
    container_name: aspnetcore-keycloak-mssqltools
    depends_on:
      - mssql
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "Abcd1234!" -Q "create database Keycloak"; do sleep 5; done'

  keycloak:
    image: jboss/keycloak
    container_name: aspnetcore-keycloak
    # restart: unless-stopped
    depends_on:
      - mssql
      - mssqlscripts
    ports:
      - 8080:8080 # http://localhost:8080 (admin/admin)
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mssql # https://github.com/keycloak/keycloak-containers/tree/master/docker-compose-examples
      - DB_USER=sa
      - DB_PASSWORD=Abcd1234!
      - DB_ADDR=mssql
      - DB_DATABASE=Keycloak

volumes:
  mssql:
    driver: local